### ISSUE TITLE
Отображаются только результаты поиска с stackoverflow

### ISSUE THREAD

**Issue by Semigradsky** [Gaserd/Gaserd_interface#1]
В консоли:
![image](https://cloud.githubusercontent.com/assets/1198848/14228852/3a38dee8-f92b-11e5-8e10-894bb5172d4b.png)

**Comment by Gaserd** [comment]
Спасибо, за Вашу находку.
В скором времени, мы уберем эти ошибки у нас на сервере.
И как только, это будет сделано, мы обязательно Вам сообщим.

**Comment by Gaserd** [comment]
@Semigradsky Доброго дня, не могли бы Вы проверить, свою проблему еще раз. На данный момент, мы переделали некоторые серверные части и тестируем их. Будем благодарны Вашей помощи.

**Comment by Semigradsky** [comment]
:+1:
